services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flexcar_development
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    command: bash -c "yarn install && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle_cache:/app/vendor/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - DATABASE_DEV_URL=postgres://postgres:password@db:5432/flexcar_ecommerce_development
      - DATABASE_TEST_URL=postgres://postgres:password@db:5432/flexcar_ecommerce_test
volumes:
  postgres_data:
  bundle_cache:
