# Use an official Ruby runtime as a parent image
FROM ruby:3.2.2

# Install dependencies
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev postgresql-client

# Create a non-root user
RUN useradd -m -s /bin/bash rails
USER rails

# Set working directory
WORKDIR /home/rails/app
RUN chown -R rails:rails /home/rails/app
RUN mkdir -p /home/rails/app/bundle_cache && chown -R rails:rails /home/rails/app/bundle_cache
ENV BUNDLE_PATH=/home/rails/app/bundle_cache

RUN bundle config set --local path '/home/rails/app/bundle_cache'

# Install Bundler
RUN gem install bundler

# Copy Gemfile and Gemfile.lock (if they exist)
COPY Gemfile* ./

# Copy the rest of the application code
COPY . .

# Expose port 3000
EXPOSE 3000

# Start the server
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
