source "https://rubygems.org"

gem "rails", "~> 8.0.2", ">= 8.0.2.1"
gem "propshaft"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "cssbundling-rails"
gem "jbuilder"

gem 'kaminari', '~> 1.2', '>= 1.2.2'

# gem "bcrypt", "~> 3.1.7"

gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

gem "bootsnap", require: false

gem "kamal", require: false

gem "thruster", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  gem "brakeman", require: false

  gem "rubocop-rails-omakase", require: false
end

group :test do
  gem 'rspec-rails', '~> 8.0', '>= 8.0.1'
  gem 'factory_bot_rails', '~> 6.5', '>= 6.5.1'
  gem 'faker', '~> 3.5', '>= 3.5.2'
  gem 'shoulda-matchers', '~> 6.0'
end

group :development do
  gem "web-console"
end
